import React, { useMemo, useState } from 'react'
import { ideaPool } from '../mockData'
import { getPlatformIcon } from '../utils/platformIcons'
import ContentDetailModal from '../components/content/ContentDetailModal'

const PLATFORMS = ['All', 'Instagram', 'X', 'YouTube', 'WhatsApp']
const STATUS_PRIORITY = {
  idea: 0,
  drafted: 1,
  published: 2,
}

function labelizeStatus(status) {
  return status.charAt(0).toUpperCase() + status.slice(1)
}

function getHighestPriorityIdea(ideas) {
  return [...ideas].sort((a, b) => {
    const statusDifference = (STATUS_PRIORITY[a.status] ?? 9) - (STATUS_PRIORITY[b.status] ?? 9)
    if (statusDifference !== 0) return statusDifference

    return new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
  })[0]
}

function getGeneratedPreview(content) {
  if (!content) return 'Belum ada preview konten.'

  try {
    const parsed = JSON.parse(content)
    return parsed.caption || parsed.description || parsed.message || parsed.hook || content
  } catch {
    return content
  }
}

export default function ContentPage({
  ideas,
  loading,
  error,
  onRetry,
  onAddIdea,
  onUpdateIdea,
  onDeleteIdea,
  onMarkDrafted,
  onMarkPublished,
  generatedContent = [],
  generatedLoading = false,
  generatedError = '',
  onRetryGeneratedContent,
  onAddGeneratedContent,
  onUpdateGeneratedContent,
  onApproveGeneratedContent,
  onPublishGeneratedContent,
  onDeleteGeneratedContent,
}) {
  const [platformFilter, setPlatformFilter] = useState('All')
  const [generating, setGenerating] = useState(false)
  const [editingId, setEditingId] = useState('')
  const [editForm, setEditForm] = useState({
    title: '',
    platform: 'Instagram',
    notes: '',
  })
  const [selectedGeneratedContent, setSelectedGeneratedContent] = useState(null)
  const stats = useMemo(() => ({
    total: ideas.length,
    drafted: ideas.filter((idea) => idea.status === 'drafted').length,
    published: ideas.filter((idea) => idea.status === 'published').length,
  }), [ideas])
  const generatedStats = useMemo(() => ({
    drafts: generatedContent.filter((item) => item.status === 'draft').length,
    approved: generatedContent.filter((item) => item.status === 'approved').length,
    published: generatedContent.filter((item) => item.status === 'published').length,
  }), [generatedContent])
  const recommendedIdea = useMemo(() => getHighestPriorityIdea(ideas), [ideas])

  const filteredIdeas = useMemo(() => {
    if (platformFilter === 'All') return ideas

    return ideas.filter((idea) => idea.platform === platformFilter)
  }, [ideas, platformFilter])

  const generateIdea = async () => {
    setGenerating(true)
    try {
      const idea = ideaPool[Math.floor(Math.random() * ideaPool.length)]
      await onAddIdea({
        platform: idea.platform,
        title: idea.text,
        format: idea.platform === 'YouTube' ? 'video' : 'post',
        status: 'idea',
        notes: 'Generated by Nexus.',
      })
    } finally {
      setGenerating(false)
    }
  }

  const startEdit = (idea) => {
    setEditingId(idea.id)
    setEditForm({
      title: idea.title || '',
      platform: idea.platform || 'Instagram',
      notes: idea.notes || '',
    })
  }

  const cancelEdit = () => {
    setEditingId('')
    setEditForm({
      title: '',
      platform: 'Instagram',
      notes: '',
    })
  }

  const saveEdit = async (ideaId) => {
    const title = editForm.title.trim()
    if (!title) return

    await onUpdateIdea(ideaId, {
      title,
      platform: editForm.platform,
      notes: editForm.notes.trim(),
    })
    cancelEdit()
  }

  return (
    <div className="page">
      <div className="page-heading">
        <div>
          <span className="eyebrow">Branding workspace</span>
          <h2>Content</h2>
        </div>
        <button className="add-task-toggle" onClick={generateIdea} disabled={generating}>
          {generating ? 'Generating...' : 'Generate Idea'}
        </button>
      </div>

      <section className="content-stats-grid">
        <div className="lead-counter-card">
          <small>Total Ideas</small>
          <strong>{stats.total}</strong>
        </div>
        <div className="lead-counter-card">
          <small>Drafted</small>
          <strong>{stats.drafted}</strong>
        </div>
        <div className="lead-counter-card">
          <small>Published</small>
          <strong>{stats.published}</strong>
        </div>
      </section>

      <section className="approval-queue-section">
        <div className="approval-queue-head">
          <div>
            <span className="eyebrow">Human approval</span>
            <h3>Approval Queue</h3>
          </div>
          {generatedLoading && <span className="queue-status">Loading...</span>}
        </div>

        <div className="content-stats-grid approval-stats-grid">
          <div className="lead-counter-card">
            <small>Drafts</small>
            <strong>{generatedStats.drafts}</strong>
          </div>
          <div className="lead-counter-card">
            <small>Approved</small>
            <strong>{generatedStats.approved}</strong>
          </div>
          <div className="lead-counter-card">
            <small>Published</small>
            <strong>{generatedStats.published}</strong>
          </div>
        </div>

        {generatedError && (
          <div className="task-empty">
            <p>{generatedError}</p>
            {onRetryGeneratedContent && (
              <button type="button" className="retry-btn" onClick={onRetryGeneratedContent}>Retry</button>
            )}
          </div>
        )}

        {!generatedLoading && !generatedError && generatedContent.length === 0 ? (
          <div className="empty-state compact-empty">Belum ada generated content.</div>
        ) : !generatedError && (
          <div className="content-groups approval-queue-list">
            {generatedContent.map((item) => {
              const platform = getPlatformIcon(item.platform)

              return (
                <article
                  className={`idea-item content-idea-card generated-content-card ${platform.colorClass}`}
                  key={item.id}
                  role="button"
                  tabIndex={0}
                  onClick={() => setSelectedGeneratedContent(item)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter') setSelectedGeneratedContent(item)
                  }}
                >
                  <div className="content-idea-main">
                    <div className="content-idea-head">
                      <span className={platform.badgeClass}>
                        <span>{platform.icon}</span>
                        {platform.label}
                      </span>
                      <span className={`content-status ${item.status}`}>{labelizeStatus(item.status)}</span>
                    </div>
                    <strong>{item.title || 'Untitled'}</strong>
                    <p className="generated-content-preview">
                      {getGeneratedPreview(item.content)}
                    </p>
                  </div>
                  <div className="content-idea-actions" onClick={(event) => event.stopPropagation()}>
                    <button type="button" onClick={() => onApproveGeneratedContent?.(item.id)}>Approve</button>
                    <button type="button" onClick={() => onPublishGeneratedContent?.(item.id)}>Publish</button>
                    <button type="button" onClick={() => onDeleteGeneratedContent?.(item.id)}>Delete</button>
                  </div>
                </article>
              )
            })}
          </div>
        )}
      </section>

      <section className="task-hint content-recommendation">
        <span className="eyebrow">📸 Rekomendasi Hari Ini</span>
        {recommendedIdea ? (
          <p>
            Platform:<br />
            {recommendedIdea.platform}<br /><br />
            Topik:<br />
            {recommendedIdea.title}<br /><br />
            Status:<br />
            {labelizeStatus(recommendedIdea.status)}
          </p>
        ) : (
          <p>Belum ada ide konten.</p>
        )}
      </section>

      <div className="content-filter-row">
        {PLATFORMS.map((platform) => (
          <button
            type="button"
            key={platform}
            className={platformFilter === platform ? 'active' : ''}
            onClick={() => setPlatformFilter(platform)}
          >
            {platform === 'All' ? 'All' : (
              <>
                <span>{getPlatformIcon(platform).icon}</span>
                {getPlatformIcon(platform).label}
              </>
            )}
          </button>
        ))}
      </div>

      {loading && <div className="task-empty">Loading content ideas...</div>}

      {error && (
        <div className="task-empty">
          <p>{error}</p>
          <button type="button" className="retry-btn" onClick={onRetry}>Retry</button>
        </div>
      )}

      {!loading && !error && filteredIdeas.length === 0 ? (
        <div className="empty-state">No ideas yet. Generate or ask Nexus to create one.</div>
      ) : !loading && !error && (
        <div className="content-groups">
          {filteredIdeas.map((idea) => {
            const platform = getPlatformIcon(idea.platform)
            const isEditing = editingId === idea.id

            return (
              <article className={`idea-item content-idea-card ${platform.colorClass}`} key={idea.id}>
                {isEditing ? (
                  <div className="content-edit-form">
                    <input
                      type="text"
                      value={editForm.title}
                      placeholder="Title"
                      onChange={(event) => setEditForm((current) => ({ ...current, title: event.target.value }))}
                    />
                    <select
                      value={editForm.platform}
                      onChange={(event) => setEditForm((current) => ({ ...current, platform: event.target.value }))}
                    >
                      {PLATFORMS.filter((item) => item !== 'All').map((item) => (
                        <option key={item} value={item}>{item}</option>
                      ))}
                    </select>
                    <textarea
                      value={editForm.notes}
                      rows={3}
                      placeholder="Notes"
                      onChange={(event) => setEditForm((current) => ({ ...current, notes: event.target.value }))}
                    />
                    <div className="content-idea-actions">
                      <button type="button" onClick={() => saveEdit(idea.id)}>Save</button>
                      <button type="button" onClick={cancelEdit}>Cancel</button>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className="content-idea-main">
                      <div className="content-idea-head">
                        <span className={platform.badgeClass}>
                          <span>{platform.icon}</span>
                          {platform.label}
                        </span>
                        <span className={`content-status ${idea.status}`}>{labelizeStatus(idea.status)}</span>
                      </div>
                      <strong>{idea.title}</strong>
                      <span>{idea.format || 'post'}</span>
                      {idea.notes && <p>{idea.notes}</p>}
                    </div>
                    <div className="content-idea-actions">
                      {idea.status === 'idea' && (
                        <button type="button" onClick={() => onMarkDrafted(idea.id)}>Mark Drafted</button>
                      )}
                      {idea.status === 'drafted' && (
                        <button type="button" onClick={() => onMarkPublished(idea.id)}>Mark Published</button>
                      )}
                      <button type="button" onClick={() => startEdit(idea)}>Edit</button>
                      <button type="button" onClick={() => onDeleteIdea(idea.id)}>Delete</button>
                    </div>
                  </>
                )}
              </article>
            )
          })}
        </div>
      )}

      <ContentDetailModal
        item={selectedGeneratedContent}
        onClose={() => setSelectedGeneratedContent(null)}
        onSave={onUpdateGeneratedContent}
        onApprove={onApproveGeneratedContent}
        onPublish={onPublishGeneratedContent}
        onDelete={onDeleteGeneratedContent}
        onDuplicate={onAddGeneratedContent}
      />
    </div>
  )
}
